---
title: "PMDD literature in Pubmed"
author: "Ana Ramos"
output: 
  flexdashboard::flex_dashboard:
    theme:
      # version: 4
      # bootswatch: minty
      bg: "#101010"
      fg: "#FDF7F7"
      primary: "#ED79F9"
      base_font:
        google: Prompt
      code_font:
        google: JetBrains Mono
    orientation: rows
    vertical_layout: scroll
runtime: shiny
---

<style>
.dataTables_scrollBody {
    height:600px !important;
    max-height:600px !important;
}
.chart-stage-flex {
    overflow:auto !important;
}
</style>


```{r setup, include=FALSE}
library(flexdashboard)
library(shinydashboard)
library(jsonlite)
library(DBI)
library(duckdb)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(shiny)
library(fresh)            # https://github.com/dreamRs/fresh
library(VennDiagram)      # https://github.com/uclahs-cds/package-VennDiagram
library(bsplus)           # https://stackoverflow.com/questions/76799976/how-to-make-accordion-type-side-bar-layout-in-shiny
library(conflicted)

conflicts_prefer(dplyr::filter)

####------------------- Pool data from database -------------------#####
# Connect to DuckDB database

database_path <- file.path('/Users', 'anaelizondo-ramos', 'Documents', 'Projects', 'pmdd', 'pmdd_pubmed',"data", "pmdd.db")
#database_path <- file.path("pmdd_pubmed", "data", "pmdd.db")

con <- dbConnect(duckdb(), dbdir = database_path)


# Get table from database and store in dataframe
publications <- dbGetQuery(con, "SELECT * FROM dim_publication_summary;")


# Close connection to database
dbDisconnect(con)



# Get categories for filter
categories <- publications %>% 
  unnest(keyterms) %>% 
  pull(keyterm_category)

categories <- c(as.character(unique(categories)))
```


```{r, inlcude = FALSE}
# Server functions


## Adapted from https://stackoverflow.com/questions/68084974/multiple-filters-shiny
  observe({
    pubs_k <- publications[publications$keyterms$keyterm_category %in% input$categories_filter,]
    #if (is.null(input$categories_filter)) {selected_choices = ""
    #}else if("All" %in% input$categories_filter) {selected_choices = publications$keyterms$keyterm
    if (is.null(input$categories_filter)) {selected_choices = publications$keyterms$keyterm
    }else selected_choices = unique(pubs_k$keyterms$keyterm)
    
    updateSelectInput(session, "keyterms_filter", choices = selected_choices)
  })
  

  ## Let's plot the publications per year
  output$pubs_year <- renderPlot({
    n_articles_year <- publications |>
      group_by(publication_year) |>
      summarize(articles = n_distinct(pubmed_id))
    
    ggplot(data = filter(n_articles_year, !is.na(publication_year))) +
      geom_col(mapping = aes(x = publication_year, y = articles), fill = "#7A6085") + 
      xlab("Publication Year") +
      ylab("Number of publications") +
      theme_classic() +
      theme(axis.text.x = element_text(size = 12),
            axis.text.y = element_text(size = 12))
  })
  
  # Venn diagram of categories
  output$keyterm_categories <- renderPlot({

    grid.draw(
      venn.diagram(
        x = list(
          publications %>% filter(keyterms$keyterm_category == "Drug Therapy") %>% select(pubmed_id) %>% unlist(), 
          publications %>% filter(keyterms$keyterm_category == "Non-Drug Therapy") %>% select(pubmed_id) %>% unlist(),
          publications %>% filter(keyterms$keyterm_category == "Symptoms") %>% select(pubmed_id) %>% unlist()
        ),
        category.names = c("Drug Therapy" , "Non-Drug Therapy" , "Symptoms"),
        filename = NULL,
        disable.logging = TRUE,
        output = FALSE,
        height = "100%",
        width = "100%",
        cat.pos = c(-27, 27, 120),
        cat.dist = c(0.055, 0.055, 0.07),
        lwd = 1,
        # col=c("#440154ff", '#21908dff', '#fde725ff'),
        # fill = c(alpha("#440154ff",0.3), alpha('#21908dff',0.3), alpha('#fde725ff',0.3)),
        col=c("#DA0E5B", '#08A072', '#E97807'),
        fill = c(alpha("#DA0E5B",0.4), alpha('#08A072',0.4), alpha('#E97807',0.4)),
        cex = 0.8,
        fontfamily = "sans",
        cat.cex = 1,
        cat.default.pos = "outer",
        cat.fontfamily = "sans",
        cat.col = c("#DA0E5B", '#08A072', '#E97807'),
        # rotation = 1
      )
    )
    
  })
  
  
  # Bar graphs of publications per keyterm
  output$pubs_keyword <- renderPlot({
    n_articles_keyterm <- publications %>%
      filter(keyterms$keyterm_category %in% coalesce(input$categories_filter, categories)) %>% 
      group_by(keyterm = keyterms$keyterm) %>% 
      summarize(articles = n_distinct(pubmed_id)) %>% 
      arrange(desc(articles))
    
    ggplot(data = head(n_articles_keyterm, n=50), aes(x = fct_reorder(keyterm, articles), y = articles) ) +
      geom_col(fill = "#907C99") +
      coord_flip() + scale_y_continuous(name="Number of publications") +
      scale_x_discrete(name="Keyterm") +
      theme_classic() +
      theme(axis.text.x = element_text(size = 12),
            axis.text.y = element_text(size = 12)
      )
  })
  
  
  # Publication summary table
  output$table <- DT::renderDataTable({   # Explore this to apply filters: https://stackoverflow.com/questions/42742788/r-shiny-filter-for-all-values
    DT::datatable(
      publications %>% 
        unnest(keyterms) %>% 
        # filter(keyterm_category %in% input$categories_filter) %>% 
        # filter(keyterm %in% coalesce(input$keyterms_filter, publications$keyterms$keyterm)) %>% 
        # {if (is.null(input$category_filter)) filter(keyterm %in% coalesce(input$keyterms_filter, publications$keyterms$keyterm))
        #  else (keyterm %in% coalesce(input$keyterms_filter, publications$keyterms$keyterm) & keyterm_category %in% input$categories_filter)} %>% 
        filter(keyterm %in% coalesce(input$keyterms_filter, publications$keyterms$keyterm) & keyterm_category %in% input$categories_filter) %>% 
        unique() %>% 
        transmute(
          PubmedID = sprintf(paste0("<a href= 'https://pubmed.ncbi.nlm.nih.gov/",pubmed_id,"/'>", pubmed_id, "</a>")),
          Title = title,
          Year = publication_year, 
          Abstract = abstract) %>% 
        arrange(desc(Year)),
      escape = FALSE)
  })
```

Historical Data
=======================================================================
Row 
-----------------------------------------------------------------------

### All time PMDD publications in Pubmed

```{r}

fillRow(height = 300, flex = c(2, 1), 
  plotOutput("pubs_year", height = 300),
  plotOutput("keyterm_categories", height = 300)
)

```

<!-- Publications -->
<!-- ======================================================================= -->
Row 
-----------------------------------------------------------------------

### Filter PMDD publications by keyterm
```{r}

fillRow(height = 600, flex = c(1, 3),

inputPanel(
  selectInput("categories_filter","Category",
                             choices = categories,
                             multiple = FALSE,
                             selectize = TRUE,
                             selected = "Non-Drug Therapy"
                             
              ),
                 
                 
  selectInput("keyterms_filter","Keyterms",
             choices = publications$keyterms$keyterm,
             multiple = FALSE,
             selected = publications %>% 
               unnest(keyterms) %>% 
               filter(keyterm_category == "Non-Drug Therapy") %>% 
               group_by(keyterm) %>% 
               summarize(publications = n_distinct(pubmed_id, na.rm = TRUE)) %>%
               arrange(desc(publications)) %>% 
               head(1) %>% 
               pull(keyterm)
              )
  ),
  plotOutput("pubs_keyword", height = 500)
)

```

Row 
-----------------------------------------------------------------------

```{r}
fillRow(height = 600, 
   DT::dataTableOutput("table", width = "100%")
)
```