# Deploy Rshiny dashboard to GitHub Pages

name: deploy_rshinyapp

on:
  # Manually trigger the workflow
  workflow_dispatch:
  # Trigger on push to `main` branch
  push:
    branches: ["main"]
  # Trigger on pull request to all branches (but do not deploy to gh-pages)
  pull_request:

jobs:
  deploy_rshinyapp:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: Render and commit dashboard
        run: |
          Rscript -e 'install.packages(c("bsplus", "conflicted", "dplyr", "DT", "flexdashboard", "fresh", "ggplot2", "ggplotify", "ggvenn", "shiny", "shinydashboard", "tidyverse", "shinylive", "httpuv"))'
          Rscript -e 'shinylive::export(appdir = "scripts/dashboard", destdir = "docs")'
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add docs/\*
          git commit -m "[Bot] Render and commit dashboard" || echo "No changes to commit"
          git push origin || echo "No changes to commit"


          